### ISSUE TITLE
Feature Request: export to CSV (and other formats)

### ISSUE THREAD

**Issue by sioodmy** [KSSidll/Arru#10]
I want to make a cli desktop client integrated with arru, but I need some way to sync data across my devices. Adding an option to export data to user specified format would allow me (and other users) to achieve that.

**Comment by KSSidll** [comment]
personally I use and would recommend [syncthing](https://github.com/syncthing/syncthing) for syncing data across devices
(you should be able to find the app data in `/storage/emulated/0/Android/data/com.kssidll.arru/files/database`)

however that's just a copy of the app database, so might not be ideal for your usecase (Arru uses sqlite)

as for export (and import) in other formats, it would certainly be a helpful feature
would make it easier for people to change apps too
