### ISSUE TITLE
[Feature Request] Light Mode

### ISSUE THREAD

**Issue by moriel5** [KSSidll/Arru#17]
Since there are those (myself included) that find light mode easier on the eyes, this would be a welcome addition.

A slight off-white would be a good option for those that also find the default material design you light mode blinding.

**Comment by KSSidll** [comment]
Arru has light theme, but it only looks at device configuration, defaulting to dark theme on devices that don't support it
So I added an in-app theme switching as part of #18 

I don't really use light theme, anywhere really, so it was a bit of an afterthought till now
#18 tries to improve it somewhat, but I don't really feel like it's good

Feedback would be appreciated

**Comment by moriel5** [comment]
Thanks, I'll make sure to test it out and leave feedback once the next version is released.

That is certainly understandable.

**Comment by moriel5** [comment]
I have tested the new version, and it is working well.

I have a few other things that are preventing me from using the app (like support for multiple currencies), however those shall be addressed via separate issues.

Regardless, thank you very much, you are doing a great job.
